### ISSUE TITLE
About Template Design

### ISSUE THREAD

**Issue by UndeadMe** [sys113/creative-agency#1]
hello dude I hope u have a great night bro

there is something that I love to explain to u maybe it doesn't matter for u :) but it's good to follow these things that i want to explain u for better Template Design maybe it's worth 

it seems that u design this template or maybe someone else or maybe the period of time to do this project was very little for u. anyway follow these:
- use better font for this template 
- dont use white for whole the button or the texts 
- learn about how can we design a dark theme ?
- the roundness of the boxes is too much or too little 
- it's better to change the footer color 
- add enough white space between sections like between `portfolio` and `People talk about us` sections 
- learn about better shadows 

I just wanted to help u in how can we design better or share my experiences about the designing to improve yourself. 
in general if u design this project as a first designing it's completely awesome.
as u know in design there is just something that can improve us and that is just mistake !  if u want to design awesome like a pro u have to design like a noob first to learn your mistakes :)

I hope you achieve your dreams bro have a good night

**Comment by hamid-shahsavani** [comment]
hello 

I got this design from the figma forum!
I tell the designer of this landing page to design better designs! D:
The points you mentioned were helpful
Thank you

**Comment by UndeadMe** [comment]
Ace dude! stay the course ❤️
